import crypto from "node:crypto";
import type { CanvasNodeType, CanvasSnapshot } from "./types.js";
import type { ToolName } from "./schemas.js";
import { nextCanvasX } from "./tools.js";

export type PlannedTool = { tool: "read" | "validate" | "apply" | "generate"; input: Record<string, unknown> };

export function planTool(name: ToolName, raw: Record<string, unknown>, state: CanvasSnapshot): PlannedTool {
    let input = { ...raw };
    if (name.startsWith("project_")) throw new Error("项目业务工具尚未开放在线 MCP 接口");
    if (["canvas_get_state", "canvas_get_context", "canvas_find_nodes", "canvas_get_node", "canvas_get_connection", "canvas_get_generation_tasks", "canvas_get_resources", "canvas_get_selection", "canvas_export_snapshot"].includes(name)) return { tool: "read", input };
    if (name === "canvas_validate_ops") return { tool: "validate", input };
    if (name === "canvas_apply_ops") return { tool: "apply", input };
    if (name === "canvas_create_workflow") input = { ...input, ops: workflowOps(input, state) };
    else if (name === "canvas_create_node") { const d = input as { nodeType: CanvasNodeType; title?: string; x?: number; y?: number; width?: number; height?: number; metadata?: Record<string, unknown> }; input = { ops: [{ type: "add_node", nodeType: d.nodeType, title: d.title, position: { x: d.x ?? nextCanvasX(state), y: d.y ?? 0 }, width: d.width, height: d.height, metadata: d.metadata }] }; }
    else if (name === "canvas_create_text_node") { const d = input as { text?: string; title?: string; x?: number; y?: number; width?: number; height?: number }; input = { ops: [textOp(d, d.x ?? nextCanvasX(state), d.y ?? 0)] }; }
    else if (name === "canvas_create_text_nodes") { const d = input as { items: Array<{ text: string; title?: string; x?: number; y?: number; width?: number; height?: number }>; x?: number; y?: number; gap?: number; direction?: "row" | "column" }; const x = d.x ?? nextCanvasX(state), y = d.y ?? 0, gap = d.gap ?? 40; input = { ops: d.items.map((item, i) => textOp(item, item.x ?? (d.direction === "row" ? x + i * (340 + gap) : x), item.y ?? (d.direction === "row" ? y : y + i * (240 + gap)))) }; }
    else if (name === "canvas_create_image_prompt_flow" || name === "canvas_create_generation_flow") input = { ...input, ops: generationFlow(input, state, name === "canvas_create_image_prompt_flow" ? "image" : undefined) };
    else if (name.startsWith("canvas_generate_")) input = { ...input, ops: generationFlow({ ...input, autoRun: true }, state, name.replace("canvas_generate_", "")) };
    else if (name === "canvas_update_node") { const d = input as { id: string; patch?: Record<string, unknown>; metadata?: Record<string, unknown> }; input = { ops: [{ type: "update_node", id: d.id, patch: d.patch, metadata: d.metadata }] }; }
    else if (name === "canvas_update_node_text") { const d = input as { id: string; text: string; title?: string }; input = { ops: [{ type: "update_node", id: d.id, patch: d.title ? { title: d.title } : {}, metadata: { content: d.text, status: "success" } }] }; }
    else if (name === "canvas_move_nodes") { const d = input as { items: Array<{ id: string; x?: number; y?: number; dx?: number; dy?: number }> }; input = { ops: d.items.map((item) => { const node = state.nodes?.find((n) => n.id === item.id); return { type: "update_node", id: item.id, patch: { position: { x: item.x ?? ((node?.position.x || 0) + (item.dx || 0)), y: item.y ?? ((node?.position.y || 0) + (item.dy || 0)) } } }; }) }; }
    else if (name === "canvas_resize_node") { const d = input as { id: string; width: number; height: number; freeResize?: boolean }; input = { ops: [{ type: "update_node", id: d.id, patch: { width: d.width, height: d.height }, metadata: d.freeResize === undefined ? undefined : { freeResize: d.freeResize } }] }; }
    else if (name === "canvas_delete_nodes") input = { ops: [{ type: "delete_node", ids: (input as { ids: string[] }).ids }] };
    else if (name === "canvas_connect_nodes") input = { ops: (input as { connections: Array<Record<string, unknown>> }).connections.map((value) => ({ type: "connect_nodes", ...value })) };
    else if (name === "canvas_select_nodes") input = { ops: [{ type: "select_nodes", ids: (input as { ids: string[] }).ids }] };
    else if (name === "canvas_set_viewport") input = { ops: [{ type: "set_viewport", viewport: (input as { viewport: unknown }).viewport }] };
    else if (name === "canvas_run_generation") { const d = input as { nodeId: string; mode?: string; prompt?: string; retry?: boolean; clientOperationId?: string; idempotencyKey?: string }; const identity = d.idempotencyKey || d.clientOperationId || stableGenerationIdentity(d); return { tool: "generate", input: { nodeId: d.nodeId, mode: d.mode || "image", prompt: d.prompt || "", retry: d.retry, clientOperationId: identity, ...(d.idempotencyKey ? { idempotencyKey: d.idempotencyKey } : {}), ...(preconditions(raw)) } }; }
    else throw new Error(`未知工具：${name}`);
    return { tool: "apply", input: { ...input, ...preconditions(raw) } };
}

function preconditions(input: Record<string, unknown>) { return { ...(typeof input.expectedRevision === "number" ? { expectedRevision: input.expectedRevision } : {}), ...(typeof input.expectedStateHash === "string" ? { expectedStateHash: input.expectedStateHash } : {}) }; }
function stableGenerationIdentity(input: { nodeId: string; mode?: string; prompt?: string; retry?: boolean }) { return `canvas-generation-${crypto.createHash("sha256").update(JSON.stringify({ nodeId: input.nodeId, mode: input.mode || "image", prompt: input.prompt || "", retry: input.retry === true })).digest("hex").slice(0, 48)}`; }
function textOp(d: { text?: string; title?: string; width?: number; height?: number }, x: number, y: number) { return { type: "add_node", nodeType: "text", title: d.title, position: { x, y }, width: d.width, height: d.height, metadata: { content: d.text || "", status: "success", fontSize: 14 } }; }
function generationFlow(input: Record<string, unknown>, state: CanvasSnapshot, forcedMode?: string) { const mode = forcedMode || (input.mode === "text" || input.mode === "video" || input.mode === "audio" ? String(input.mode) : "image"); const prompt = String(input.prompt || ""); const x = Number(input.x ?? nextCanvasX(state)), y = Number(input.y ?? 0), textId = `text-${crypto.randomUUID()}`, targetId = `${mode}-${crypto.randomUUID()}`, refs = Array.isArray(input.referenceNodeIds) ? input.referenceNodeIds.filter((v): v is string => typeof v === "string") : []; const nodeType = mode === "video" ? "video" : mode === "audio" ? "audio" : mode === "text" ? "text" : "image"; return [textOp({ text: prompt, title: String(input.title || "提示词") }, x, y), { type: "add_node", id: targetId, nodeType, title: String(input.title || `${mode}生成`), position: { x: x + 420, y }, width: 420, height: 320, metadata: { composerContent: `@[node:${textId}]\n${refs.map((id) => `@[node:${id}]`).join("\n")}`, prompt, generationMode: mode, status: "idle" } }, { type: "connect_nodes", fromNodeId: textId, toNodeId: targetId }, ...refs.map((id) => ({ type: "connect_nodes", fromNodeId: id, toNodeId: targetId })), { type: "select_nodes", ids: [targetId] }, ...(input.autoRun ? [{ type: "run_generation", id: `generation-${crypto.randomUUID()}`, nodeId: targetId, mode, prompt }] : [])]; }
function workflowOps(input: Record<string, unknown>, state: CanvasSnapshot) { const nodes = Array.isArray(input.nodes) ? input.nodes as Array<Record<string, unknown>> : []; if (!nodes.length) throw new Error("工作流至少需要一个节点"); const ids = new Map(nodes.map((n) => [String(n.ref), `agent-workflow-${crypto.randomUUID().slice(0, 8)}-${String(n.ref).replace(/[^a-z0-9\u4e00-\u9fff]/gi, "-").slice(0, 24)}`])); const ops: Record<string, unknown>[] = []; let x = Number((input.start as { x?: number } | undefined)?.x ?? nextCanvasX(state)), y = Number((input.start as { y?: number } | undefined)?.y ?? 80); const vertical = input.direction === "vertical"; for (const n of nodes) { const kind = String(n.kind || "text"), type = kind === "script" ? "script" : ["image", "character_cards", "character_three_view"].includes(kind) ? "image" : ["video", "storyboard_video"].includes(kind) ? "video" : kind === "audio" ? "audio" : "text"; const prompt = String(n.prompt || n.content || (type === "text" || type === "script" ? "" : `${String(input.title || "当前创作项目")}：${String(n.title || kind)}`)); ops.push({ type: "add_node", id: ids.get(String(n.ref)), nodeType: type, title: String(n.title || kind), position: { x, y }, width: type === "video" ? 640 : type === "image" ? 560 : 420, height: type === "video" ? 360 : type === "image" ? 380 : 240, metadata: { content: type === "text" || type === "script" ? String(n.content || prompt) : "", prompt, composerContent: prompt, workflowKind: kind, status: type === "text" || type === "script" ? "success" : "idle" } }); vertical ? y += type === "video" ? 408 : 428 : x += type === "video" ? 768 : 668; } const edges = Array.isArray(input.edges) && input.edges.length ? input.edges as Array<Record<string, unknown>> : nodes.slice(0, -1).map((n, i) => ({ from: n.ref, to: nodes[i + 1].ref })); for (const edge of edges) ops.push({ type: "connect_nodes", fromNodeId: ids.get(String(edge.from)), toNodeId: ids.get(String(edge.to)) }); ops.push({ type: "select_nodes", ids: nodes.map((n) => ids.get(String(n.ref))) }); if (input.autoRun === true) for (const n of nodes) { const id = ids.get(String(n.ref)), kind = String(n.kind || ""); if (["image", "video", "audio", "character_cards", "character_three_view", "storyboard_video"].includes(kind)) ops.push({ type: "run_generation", id: `generation-${crypto.randomUUID()}`, nodeId: id, mode: kind.includes("video") ? "video" : kind.includes("audio") ? "audio" : "image", prompt: String(n.prompt || n.content || "") }); } return ops; }
